[build]
base = "/"
command = "npx astro build"
publish = "dist"
functions = "api"

[build.environment]
PLATFORM = "netlify"
PUBLIC_API_ENDPOINT = "/.netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 301
force = true

[[plugins]]
package = "netlify-plugin-chromium"

[plugins.inputs]
packageManager = "yarn"

[[headers]]
for = "/*"

[headers.values]